"""add prioridade na tarefa

Revision ID: 3af69e33991b
Revises: 5ee9df2b5439
Create Date: 2026-06-28 15:21:54.560223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel usa tipos proprios (AutoString) nas colunas


# revision identifiers, used by Alembic.
revision: str = '3af69e33991b'
down_revision: Union[str, Sequence[str], None] = '5ee9df2b5439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tarefa', sa.Column('prioridade', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tarefa', 'prioridade')
    # ### end Alembic commands ###
