"""add descricao na categoria

Revision ID: 5ee9df2b5439
Revises: f579fb0d6772
Create Date: 2026-06-28 15:14:07.272369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel usa tipos proprios (AutoString) nas colunas


# revision identifiers, used by Alembic.
revision: str = '5ee9df2b5439'
down_revision: Union[str, Sequence[str], None] = 'f579fb0d6772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categoria', sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categoria', 'descricao')
    # ### end Alembic commands ###
