"""schema inicial

Revision ID: f579fb0d6772
Revises:
Create Date: 2026-06-28 15:02:34.107262

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # SQLModel usa tipos proprios (AutoString) nas colunas

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f579fb0d6772"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categoria",
        sa.Column("nome", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "usuario",
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("senha_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tarefa",
        sa.Column("titulo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("feita", sa.Boolean(), nullable=False),
        sa.Column("categoria_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["categoria_id"],
            ["categoria.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tarefa")
    op.drop_table("usuario")
    op.drop_table("categoria")
    # ### end Alembic commands ###
